/**
 * @file types.ts
 * @description Canonical type definitions for the ZombieRun Crash game engine.
 *
 * This file is the single source of truth for:
 *  - Server → Client event payloads
 *  - Client → Server event payloads
 *  - Internal game state shape
 *
 * Both the server (Phase 2) and the client (Phase 4) import from here
 * to guarantee payload shape parity and eliminate a class of runtime bugs.
 */

// ─── Game Phase Enum ──────────────────────────────────────────────────────────

export enum GamePhase {
  /** Seeds generated, hash published, waiting for betting window */
  IDLE    = 'IDLE',
  /** 10-second window for players to place bets */
  BETTING = 'BETTING',
  /** Multiplier is climbing; auto-cashouts are being processed */
  RUNNING = 'RUNNING',
  /** Round over; results being finalised */
  CRASHED = 'CRASHED',
}

// ─── Internal State Machine Shape ────────────────────────────────────────────

export interface GameState {
  phase:           GamePhase;
  roundId:         string;    // MongoDB ObjectId hex
  roundNumber:     number;
  /** SHA-256 of serverSeed — broadcast at BETTING start */
  serverSeedHash:  string;
  /** Populated after crash, for Provably Fair reveal */
  serverSeed?:     string;
  hmacHex?:        string;
  clientSeed:      string;    // XOR-aggregated from all betting players
  nonce:           number;
  /** Predetermined crash point — known by server only until round ends */
  crashMultiplier: number;
  /** Unix ms when RUNNING phase began */
  runningStartedAt: number;
  /** Active bets: userId → bet document id + amount + autoCashoutAt */
  activeBets:       Map<string, ActiveBetEntry>;
}

export interface ActiveBetEntry {
  betId:         string;   // MongoDB Bet._id hex
  userId:        string;
  amountCents:   number;
  autoCashoutAt: number;   // 0 = manual only
  cashedOut:     boolean;
}

// ─── Server → Client Events ───────────────────────────────────────────────────

/**
 * Emitted when a new round's betting window opens.
 * Clients use serverSeedHash to verify the seed was committed before bets.
 */
export interface S2C_BettingStarted {
  roundNumber:    number;
  roundId:        string;
  serverSeedHash: string;
  /** Milliseconds until RUNNING phase begins */
  bettingEndsInMs: number;
  /** Last N crash results for the history ticker */
  recentCrashes:  number[];
}

/**
 * Emitted the moment the multiplier starts climbing.
 * The client starts its animation loop from this event.
 */
export interface S2C_RoundStarted {
  roundNumber:     number;
  roundId:         string;
  serverSeedHash:  string;
  runningStartedAt: number; // Unix ms — used for client-side multiplier interpolation
}

/**
 * High-frequency tick (~100ms) broadcasting the current multiplier.
 * The client uses `runningStartedAt` + local clock for smooth interpolation
 * between ticks, so the actual tick rate is less critical for visual fidelity.
 */
export interface S2C_MultiplierTick {
  multiplier:  number;
  elapsedMs:   number;
}

/**
 * Emitted when the round crashes.
 * Reveals the server seed so players can independently verify the outcome.
 */
export interface S2C_RoundCrashed {
  roundNumber:     number;
  crashMultiplier: number;
  /** Now revealed for Provably Fair verification */
  serverSeed:      string;
  hmacHex:         string;
  clientSeed:      string;
  nonce:           number;
  totalBetsCents:  number;
  totalPayoutCents: number;
  playerCount:     number;
}

/**
 * Sent to a specific player socket when their bet is accepted.
 */
export interface S2C_BetAccepted {
  betId:           string;
  roundNumber:     number;
  amountCents:     number;
  autoCashoutAt:   number;
  idempotencyKey:  string;
  newBalanceCents: number;
}

/**
 * Sent to a specific player socket when their cashout is processed.
 */
export interface S2C_CashoutConfirmed {
  betId:              string;
  cashoutMultiplier:  number;
  payoutCents:        number;
  profitCents:        number;
  newBalanceCents:    number;
}

/**
 * Error response for PLACE_BET or CASH_OUT failures.
 */
export interface S2C_Error {
  code:    string;
  message: string;
  /** Original idempotency key, for client-side deduplication tracking */
  idempotencyKey?: string;
}

/** List of active bets in the current round (censored — only amounts shown) */
export interface S2C_BetList {
  bets: PublicBetEntry[];
}

export interface PublicBetEntry {
  username:    string;
  amountCents: number;
  /** null while still active, multiplier value once cashed out */
  cashoutAt:   number | null;
}

// ─── Client → Server Events ───────────────────────────────────────────────────

/**
 * Player places a bet during the BETTING phase.
 * idempotencyKey is a UUID v4 generated by the client before sending.
 * If the same key is received twice, the server processes it once and
 * returns BetAccepted both times (idempotent).
 */
export interface C2S_PlaceBet {
  amountCents:    number;
  autoCashoutAt:  number;   // 0 = manual
  idempotencyKey: string;   // UUID v4
}

/**
 * Player manually cashes out during the RUNNING phase.
 * cashoutIdempotencyKey prevents double cashouts on retry.
 */
export interface C2S_CashOut {
  betId:                   string;
  cashoutIdempotencyKey:   string;   // UUID v4
}

// ─── Socket.IO Map Types ──────────────────────────────────────────────────────
// These are passed to the generic Server<> / Socket<> constructors
// in Phase 2 to get full intellisense on emit() and on() calls.

export interface ServerToClientEvents {
  'betting:started':   (data: S2C_BettingStarted)   => void;
  'round:started':     (data: S2C_RoundStarted)      => void;
  'multiplier:tick':   (data: S2C_MultiplierTick)    => void;
  'round:crashed':     (data: S2C_RoundCrashed)      => void;
  'bet:accepted':      (data: S2C_BetAccepted)       => void;
  'cashout:confirmed': (data: S2C_CashoutConfirmed)  => void;
  'bet:list':          (data: S2C_BetList)            => void;
  'error':             (data: S2C_Error)              => void;
  'reconnect:state':   (data: ReconnectStatePayload) => void;
}

export interface ClientToServerEvents {
  'bet:place':   (data: C2S_PlaceBet, ack: AckCallback) => void;
  'bet:cashout': (data: C2S_CashOut,  ack: AckCallback) => void;
}

export interface InterServerEvents {
  // Reserved for future horizontal scaling with Redis adapter
}

export interface SocketData {
  userId:   string;
  username: string;
  role:     string;
}

/** Generic acknowledgement callback for client-initiated events */
export type AckCallback = (response: { ok: boolean; error?: S2C_Error }) => void;

/**
 * Sent to a reconnecting client so it can restore UI state
 * without waiting for the next phase transition event.
 */
export interface ReconnectStatePayload {
  phase:           GamePhase;
  roundNumber:     number;
  serverSeedHash:  string;
  runningStartedAt?: number;
  currentMultiplier?: number;
  bettingEndsInMs?:   number;
  recentCrashes:   number[];
}
