/**
 * @file Bet.model.ts
 * @description Mongoose model for a single player bet within a GameRound.
 *
 * Idempotency:
 *   - `idempotencyKey` (UUID v4 provided by the client) is indexed as unique
 *     per-round to block double-spend on reconnect / request retry.
 *
 * Lifecycle:
 *   active → cashed_out   (player pressed cash-out before crash)
 *   active → lost         (round crashed while bet was still active)
 *   active → refunded     (round aborted due to server error)
 */

import { Schema, model, Document, Types } from 'mongoose';

// ─── Enums ────────────────────────────────────────────────────────────────────

export enum BetStatus {
  ACTIVE    = 'active',
  CASHED_OUT = 'cashed_out',
  LOST      = 'lost',
  REFUNDED  = 'refunded',
}

// ─── Interfaces ───────────────────────────────────────────────────────────────

export interface IBet extends Document {
  _id:         Types.ObjectId;

  // ── Relations ───────────────────────────────────────────────────────────────
  userId:      Types.ObjectId;
  roundId:     Types.ObjectId;
  roundNumber: number;   // denormalized for quick lookups

  // ── Bet Details ─────────────────────────────────────────────────────────────
  /** Amount wagered in integer cents */
  amountCents:   number;
  /** Auto cash-out multiplier set by the player (0 = manual only) */
  autoCashoutAt: number;

  // ── Outcome ─────────────────────────────────────────────────────────────────
  status:           BetStatus;
  /** Multiplier at which the player cashed out (0 if lost) */
  cashoutMultiplier: number;
  /** Net payout in integer cents (0 if lost) */
  payoutCents:       number;
  /** Profit/loss in integer cents */
  profitCents:       number;

  // ── Idempotency ─────────────────────────────────────────────────────────────
  /** UUID v4 generated by the client; ensures exactly-once bet processing */
  idempotencyKey: string;
  /** UUID v4 for the cash-out action; ensures exactly-once cashout processing */
  cashoutIdempotencyKey?: string;

  // ── Timestamps ──────────────────────────────────────────────────────────────
  placedAt:    Date;
  cashedOutAt?: Date;
  createdAt:   Date;
  updatedAt:   Date;

  // ── Audit ───────────────────────────────────────────────────────────────────
  /** IP address of the bet request for fraud detection */
  clientIp?: string;
}

// ─── Schema ───────────────────────────────────────────────────────────────────

const BetSchema = new Schema<IBet>(
  {
    userId: {
      type:     Schema.Types.ObjectId,
      ref:      'User',
      required: true,
      index:    true,
    },
    roundId: {
      type:     Schema.Types.ObjectId,
      ref:      'GameRound',
      required: true,
      index:    true,
    },
    roundNumber: { type: Number, required: true },

    // Bet Details
    amountCents: {
      type:     Number,
      required: true,
      min:      1,   // minimum 1 cent bet
    },
    autoCashoutAt: {
      type:    Number,
      default: 0,    // 0 means player will cash out manually
      min:     0,
    },

    // Outcome (set after round resolution)
    status: {
      type:    String,
      enum:    Object.values(BetStatus),
      default: BetStatus.ACTIVE,
      index:   true,
    },
    cashoutMultiplier: { type: Number, default: 0 },
    payoutCents:       { type: Number, default: 0 },
    profitCents:       { type: Number, default: 0 },

    // Idempotency
    idempotencyKey: {
      type:     String,
      required: true,
      // Unique per round to allow the same UUID to be reused across rounds
      // (enforced via compound index below)
    },
    cashoutIdempotencyKey: { type: String },

    // Timestamps
    placedAt:    { type: Date, default: () => new Date() },
    cashedOutAt: { type: Date },

    // Audit
    clientIp: { type: String },
  },
  {
    timestamps: true,
    versionKey: '__v',
  },
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

/**
 * Core idempotency index: prevents the same client from placing the same
 * bet twice within a single round, even under network retry pressure.
 */
BetSchema.index({ idempotencyKey: 1, roundId: 1 }, { unique: true });

/** Cashout idempotency: one cashout action per bet */
BetSchema.index({ cashoutIdempotencyKey: 1 }, { unique: true, sparse: true });

/** User bet history queries */
BetSchema.index({ userId: 1, createdAt: -1 });

/** Admin round inspection */
BetSchema.index({ roundId: 1, status: 1 });

/** Analytics / leaderboard */
BetSchema.index({ payoutCents: -1 });
BetSchema.index({ profitCents: -1 });

// ─── Export ───────────────────────────────────────────────────────────────────

export const BetModel = model<IBet>('Bet', BetSchema);
